FROM ghcr.io/mysociety/data_common:sha-03168b5

# Make an empty project directory so the 'self' setup doesn't fail and scripts can be setup
# Override the .pth created at previous stages to point to where the working directory will land
COPY pyproject.toml /setup/ 
COPY src/data_common/pyproject.toml /setup/src/data_common/
RUN mkdir /setup/src/procurement_data && touch /setup/src/procurement_data/__init__.py \
    && touch /setup/src/data_common/__init__.py \
    && export PATH="$HOME/.poetry/bin:$PATH" \
    && cd /setup/ && poetry install \
    && echo "/workspaces/procurement_data/src/" > /usr/local/lib/python3.10/site-packages/procurement_data.pth \
    && echo "/workspaces/procurement_data/src/data_common/src" > /usr/local/lib/python3.10/site-packages/data_common.pth
